### ISSUE TITLE
Issue in attendance page

### ISSUE THREAD

**Issue by SargaManandhar** [SargaManandhar/Attendance-system#10]
![111](https://user-images.githubusercontent.com/81401605/118365364-2e49ce00-b5bc-11eb-80bd-c2419fa70678.png)
There is no option to choose or input date

**Comment by Suniltmg** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date 
Here is some link that might be helpful to solve this issue. Please, read it.

**Comment by Bramhananda-B** [comment]
An input field has been added to store date along with other details in database.
