### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by SargaManandhar** [SargaManandhar/Attendance-system#11]
![186870597_499118864572644_1864799952073985022_n](https://user-images.githubusercontent.com/81401605/118367167-ae723280-b5c0-11eb-91a6-d4326b8c6894.png)
There should be teacher's name and module in the form

**Comment by Nischal299** [comment]
ok, i have fixed the issue. I have changed the form with teacher's name and module
![issue3Solved](https://user-images.githubusercontent.com/81400961/118368157-5687fb80-b5c1-11eb-9cae-6a089200bcf6.png)
