### ISSUE TITLE
Issue in class button 

### ISSUE THREAD

**Issue by SargaManandhar** [SargaManandhar/Attendance-system#12]
![image](https://user-images.githubusercontent.com/81401605/118394609-6eb15680-b665-11eb-8931-5bf40a7318c4.png)
Class button doesnot on teacher's board doesnot have option to chose or input class

**Comment by Bramhananda-B** [comment]
![class](https://user-images.githubusercontent.com/81401183/118395526-9951de00-b66a-11eb-8829-46f3f1dd181b.png)

A field for classes was added

**Comment by Bramhananda-B** [comment]
![field for class](https://user-images.githubusercontent.com/81401183/118395550-bdadba80-b66a-11eb-9251-52b7dbd1ab78.png)
Field was added for classes
