### ISSUE TITLE
Error in landing page

### ISSUE THREAD

**Issue by SargaManandhar** [SargaManandhar/Attendance-system#2]
When clicking the teacher in the landing page, the page goes to teachers  dashboard directly instead of login page.
![preview-chat-index](https://user-images.githubusercontent.com/81401605/114817833-6c47ac80-9dda-11eb-953b-ada86393de49.png)
![Capture](https://user-images.githubusercontent.com/81401605/114818076-d82a1500-9dda-11eb-853a-595efa02418b.JPG)

**Comment by Nischal299** [comment]
I have solved the issue. Now while clicking the teacher option it will open teacher login or sign up page.
![issuesolved](https://user-images.githubusercontent.com/81400961/114861945-aa11f880-9e0d-11eb-81ea-dd23c76fa47f.png)
