### ISSUE TITLE
Error in Student page

### ISSUE THREAD

**Issue by SargaManandhar** [SargaManandhar/Attendance-system#3]
There should not be account section in the student page
![studentIssue](https://user-images.githubusercontent.com/81401605/114973300-e2faad80-9e9f-11eb-9925-72032314affd.png)

**Comment by Nischal299** [comment]
I have removed the account section from the student's page
![StudentIssueSolved](https://user-images.githubusercontent.com/81400961/114973732-c14df600-9ea0-11eb-89ec-47f019203186.png)
