### ISSUE TITLE
options are not at the center of the box 

### ISSUE THREAD

**Issue by Aashishguiday** [SargaManandhar/Attendance-system#4]
![173824504_2912861028994696_1865074799671744957_n](https://user-images.githubusercontent.com/81401240/115009211-c5433d80-9ecb-11eb-836d-9a5fa57672ea.jpg)

**Comment by Bramhananda-B** [comment]
![solved issue](https://user-images.githubusercontent.com/81401183/115010076-b610bf80-9ecc-11eb-849d-c36b7fb13a09.jpg)
The issue was solved using the styling { text-align: center;} on h1
