### ISSUE TITLE
Issue in rendering to register.html

### ISSUE THREAD

**Issue by SargaManandhar** [SargaManandhar/Attendance-system#5]
Rendering to register.html not working.
![186509995_311932980338936_5227063082091493751_n](https://user-images.githubusercontent.com/81401605/118300710-f7af7d00-b501-11eb-8579-76d6b17dffd7.png)

**Comment by Suniltmg** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/81401584/118346754-51916080-b55d-11eb-8049-d17756819b9f.png)

Register page was not rendering because I try to create return render to my login page after registering the user. Now, the issue has been solved.
