### ISSUE TITLE
Issue in details

### ISSUE THREAD

**Issue by SargaManandhar** [SargaManandhar/Attendance-system#6]
W
![Capture](https://user-images.githubusercontent.com/81401605/118354272-10637580-b58a-11eb-9513-0d6b2119a233.JPG)
hile viewing the class,  it shows teachers' details instead of student's details

**Comment by Nischal299** [comment]
I have fixed the issue. Now it shows the student's detail page 
![issue1Solved](https://user-images.githubusercontent.com/81400961/118355322-160f8a00-b58f-11eb-8505-57ca345b7428.png)
