### ISSUE TITLE
Issue in admin dashboard

### ISSUE THREAD

**Issue by SargaManandhar** [SargaManandhar/Attendance-system#7]
T
![issue2](https://user-images.githubusercontent.com/81401605/118357639-f1b9aa80-b59a-11eb-919a-033110bb536a.png)
here should be a  add teacher page in admin's dashboard

**Comment by Nischal299** [comment]
i have added the add teacher page. 
![issue2Solved](https://user-images.githubusercontent.com/81400961/118362844-1fa9e980-b5b1-11eb-8fc5-e7846d574d74.png)
