### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by SargaManandhar** [SargaManandhar/Attendance-system#8]
![111](https://user-images.githubusercontent.com/81401605/118364673-2dfc0380-b5b9-11eb-936a-7749baa1489c.png)
![222](https://user-images.githubusercontent.com/81401605/118364678-33594e00-b5b9-11eb-8c6a-dea2865253f0.png)
 There has been an issue in this section

**Comment by Nischal299** [comment]
i think the path is mistake. Can you guys correct the path of the image

**Comment by Suniltmg** [comment]
ok @Nischal299  i will try to put image also

**Comment by Suniltmg** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/81401584/118383985-7b608b00-b622-11eb-8b7a-744fb05344b6.png)
I have solved the issue of not rendering from one html to other html.
